language: python

before_script:
    - wget 'https://github.com/gohugoio/hugo/releases/download/v0.72.0/hugo_0.72.0_Linux-64bit.tar.gz'
    - tar -xvf hugo_0.72.0_Linux-64bit.tar.gz -C /usr/bin
    - chmod -x $HOME/hugo
    - pip install nbconvert

script:
   - |
    for file in content/notebooks/*.ipynb; do
      python -m nbconvert "$file --to markdown --output content/posts/$(basename $file).md" || continue
    done
   - hugo


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: public
  on:
    branch: master
